name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y cmake libopencv-dev

    - name: Configure CMake Build
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build
